### ISSUE TITLE
Support version ranges in caniuse-db

### ISSUE THREAD

**Issue by papandreou** [Munter/express-legacy-csp#4]
I overlooked these: https://github.com/Fyrd/caniuse/blob/1bbd1ceb806f87e167d42751ce31130dda4cf5b6/features-json/contentsecuritypolicy2.json#L169

**Comment by Munter** [comment]
Fixed in #5 ?

**Comment by papandreou** [comment]
Yup :)

**Comment by Munter** [comment]
Released in v1.2.0
