### ISSUE TITLE
Remove directives that a browser doesn't understand?

### ISSUE THREAD

**Issue by Munter** [Munter/express-legacy-csp#9]
I'm getting these CSP errors in Safari 9.1:

![image](https://cloud.githubusercontent.com/assets/331790/23582351/76f1a03a-0128-11e7-9712-5a96bb4d5333.png)

Should we consider stripping non-supported directives as part of downgrading a CSP to a lower version?

**Comment by papandreou** [comment]
Hmm, that sounds like a great idea!

**Comment by papandreou** [comment]
Avoiding those warnings would be a great selling point.

**Comment by papandreou** [comment]
Also `frame-ancestors` in newer Safaris.
